version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
