# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X "github.com/stknohg/ec2rdp/cmd.cmdVersion={{.Version}}"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}-
      {{- tolower .Os }}-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: 
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^fix.{0,1}$'
brews:
 - tap:
    owner: stknohg
    name: homebrew-tap
    branch: main
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
   description: "Remote Desktop Utility for Amazon EC2."
   homepage: "https://github.com/stknohg/ec2rdp"
   license: "MIT"
   folder: Formula
