version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -w -s
      - -X "github.com/stknohg/ec2rdp/cmd.cmdVersion={{.Version}}"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}-
      {{- tolower .Os }}-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: 
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^fix.{0,1}$'
brews:
  - 
    description: "Remote Desktop Utility for Amazon EC2."
    homepage: "https://github.com/stknohg/ec2rdp"
    license: "MIT"
    directory: Formula
    repository:
      owner: stknohg
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
scoops:
  - 
    description: "Remote Desktop Utility for Amazon EC2."
    homepage: "https://github.com/stknohg/ec2rdp"
    license: "MIT"
    directory: bucket
    url_template: "https://github.com/stknohg/ec2rdp/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    shortcuts: [["ec2rdp.exe", "ec2rdp"]]
    repository:
      owner: stknohg
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
