name: Build and Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.yaml'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Currently, this app only supports Windows and MacOS.
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
